### ISSUE TITLE
filter out party hubs

### ISSUE THREAD

**Issue by JuriRappsilber** [Rappsilber-Laboratory/crosslink-viewer#20]
Proteins that link to many others tend to be few but contribute to the hair ball issue heavily while being often not so informative. Could one set a "low pass" filter, filtering out proteins above a set number of interactors, to be specified by the user, e.g. 10.

**Comment by colin-combe** [comment]
This was discussed recently (this year sometime) in a meeting and I think the conclusion was this didn't need automated, hub proteins can be manually filtered out
